version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/tomcat8/webapps/ROOT
hooks:
  BeforeInstall:
    - location: codedeploy-scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy-scripts/stop_server.sh
      timeout: 300
      runas: root
